kind: pipeline
#type: kubernetes
name: default

steps:
  - name: bake-development
    image: plugins/docker
    settings:
      username:
        from_secret: docker_user
      password:
        from_secret: docker_pass
      repo: registry.nestorrente.com/v2/erdiagram/erdiagram-playground
      registry: registry.nestorrente.com/v2
      tags:
        - 1.0.0.${CI_BUILD_NUMBER}-SNAPSHOT
    when:
      branch:
        - develop
        - develop-rc2
  - name: bake-production
    image: plugins/docker
    settings:
      username:
        from_secret: docker_user
      password:
        from_secret: docker_pass
      repo: registry.nestorrente.com/v2/erdiagram/erdiagram-playground
      registry: registry.nestorrente.com/v2
      tags:
        - latest
        - 1.0.0.${CI_BUILD_NUMBER}
    when:
      branch:
        - master
        - release/*
  - name: deploy-dev
    image: rubasace/drone-helm-k8s
    environment:
      K8S_CERT_AUTHORITY_DATA:
        from_secret: K8S_CERT_AUTHORITY_DATA
      K8S_SERVER:
        from_secret: K8S_SERVER
      K8S_USER:
        from_secret: K8S_USER
      K8S_PASSWORD:
        from_secret: K8S_PASSWORD
      NAMESPACE: development
      IMAGE_TAG: 1.0.0.${CI_BUILD_NUMBER}-SNAPSHOT
    when:
      branch:
        - develop
        - develop-rc2
  - name: deploy-production
    image: rubasace/drone-helm-k8s
    environment:
      K8S_CERT_AUTHORITY_DATA:
        from_secret: K8S_CERT_AUTHORITY_DATA
      K8S_SERVER:
        from_secret: K8S_SERVER
      K8S_USER:
        from_secret: K8S_USER
      K8S_PASSWORD:
        from_secret: K8S_PASSWORD
      NAMESPACE: production
      IMAGE_TAG: 1.0.0.${CI_BUILD_NUMBER}
    when:
      branch:
        - master
