import {
	ClassModelGeneratorSerializableConfig,
	ClassModelToCodeConverterSerializableConfig,
	DatabaseModelGeneratorSerializableConfig,
	EntityRelationshipModelParserSerializableConfig,
	JavaClassModelToCodeConverterSerializableConfig,
	MysqlDialectSerializableConfig,
	NomnomlEntityRelationshipModelToDiagramCodeConverterSerializableConfig,
	OracleDialectSerializableConfig,
	PostgresqlDialectSerializableConfig,
	SqlDialectSerializableConfig,
	SqliteDialectSerializableConfig,
	SqlServerDialectSerializableConfig,
	TypeScriptClassModelToCodeConverterSerializableConfig
} from '@nestorrente/erdiagram';

export default interface ERDiagramPlaygroundSerializableConfig {
	_version: string;
	erModelParser: EntityRelationshipModelParserSerializableConfig;
	mysql: DatabaseDialectSerializableConfig<MysqlDialectSerializableConfig>;
	oracle: DatabaseDialectSerializableConfig<OracleDialectSerializableConfig>;
	postgresql: DatabaseDialectSerializableConfig<PostgresqlDialectSerializableConfig>;
	sqlite: DatabaseDialectSerializableConfig<SqliteDialectSerializableConfig>;
	sqlserver: DatabaseDialectSerializableConfig<SqlServerDialectSerializableConfig>;
	java: ClassLanguageSerializableConfig<JavaClassModelToCodeConverterSerializableConfig>;
	typescript: ClassLanguageSerializableConfig<TypeScriptClassModelToCodeConverterSerializableConfig>;
	nomnoml: NomnomlEntityRelationshipModelToDiagramCodeConverterSerializableConfig;
}

export interface DatabaseDialectSerializableConfig<T extends SqlDialectSerializableConfig> {
	databaseModelGeneratorConfig: DatabaseModelGeneratorSerializableConfig;
	databaseModelToCodeConverterConfig: T;
}

export interface ClassLanguageSerializableConfig<T extends ClassModelToCodeConverterSerializableConfig> {
	classModelGeneratorConfig: ClassModelGeneratorSerializableConfig;
	classModelToCodeConverterConfig: T;
}
